export const DEFAULT_SUGGESTIONS: { n: string; c: string }[] = [
  { n: 'Acqua', c: 'Spesa' },
  { n: 'Pane', c: 'Spesa' },
  { n: 'Pasta', c: 'Spesa' },
  { n: 'Riso', c: 'Spesa' },
  { n: 'Pomodori', c: 'Spesa' },
  { n: 'Insalata', c: 'Spesa' },
  { n: 'Zucchine', c: 'Spesa' },
  { n: 'Melanzane', c: 'Spesa' },
  { n: 'Peperoni', c: 'Spesa' },
  { n: 'Carote', c: 'Spesa' },
  { n: 'Cipolle', c: 'Spesa' },
  { n: 'Aglio', c: 'Spesa' },
  { n: 'Patate', c: 'Spesa' },
  { n: 'Funghi', c: 'Spesa' },
  { n: 'Spinaci', c: 'Spesa' },
  { n: 'Broccoli', c: 'Spesa' },
  { n: 'Mele', c: 'Spesa' },
  { n: 'Banane', c: 'Spesa' },
  { n: 'Arance', c: 'Spesa' },
  { n: 'Limoni', c: 'Spesa' },
  { n: 'Uva', c: 'Spesa' },
  { n: 'Fragole', c: 'Spesa' },
  { n: 'Pere', c: 'Spesa' },
  { n: 'Kiwi', c: 'Spesa' },
  { n: 'Pollo', c: 'Spesa' },
  { n: 'Carne macinata', c: 'Spesa' },
  { n: 'Salsicce', c: 'Spesa' },
  { n: 'Prosciutto cotto', c: 'Spesa' },
  { n: 'Prosciutto crudo', c: 'Spesa' },
  { n: 'Salame', c: 'Spesa' },
  { n: 'Mortadella', c: 'Spesa' },
  { n: 'Tonno in scatola', c: 'Spesa' },
  { n: 'Salmone', c: 'Spesa' },
  { n: 'Latte', c: 'Spesa' },
  { n: 'Yogurt', c: 'Spesa' },
  { n: 'Burro', c: 'Spesa' },
  { n: 'Mozzarella', c: 'Spesa' },
  { n: 'Parmigiano', c: 'Spesa' },
  { n: 'Ricotta', c: 'Spesa' },
  { n: 'Uova', c: 'Spesa' },
  { n: 'Passata di pomodoro', c: 'Spesa' },
  { n: 'Olio d\'oliva', c: 'Spesa' },
  { n: 'Aceto', c: 'Spesa' },
  { n: 'Sale', c: 'Spesa' },
  { n: 'Pepe', c: 'Spesa' },
  { n: 'Zucchero', c: 'Spesa' },
  { n: 'Farina', c: 'Spesa' },
  { n: 'Caffè', c: 'Spesa' },
  { n: 'Tè', c: 'Spesa' },
  { n: 'Biscotti', c: 'Spesa' },
  { n: 'Fette biscottate', c: 'Spesa' },
  { n: 'Marmellata', c: 'Spesa' },
  { n: 'Nutella', c: 'Spesa' },
  { n: 'Miele', c: 'Spesa' },
  { n: 'Cornflakes', c: 'Spesa' },
  { n: 'Snack', c: 'Spesa' },
  { n: 'Patatine', c: 'Spesa' },
  { n: 'Pizza', c: 'Spesa' },
  { n: 'Dentifricio', c: 'Igiene' },
  { n: 'Spazzolino', c: 'Igiene' },
  { n: 'Collutorio', c: 'Igiene' },
  { n: 'Sapone mani', c: 'Igiene' },
  { n: 'Sapone doccia', c: 'Igiene' },
  { n: 'Shampoo', c: 'Igiene' },
  { n: 'Balsamo', c: 'Igiene' },
  { n: 'Deodorante', c: 'Igiene' },
  { n: 'Crema viso', c: 'Igiene' },
  { n: 'Crema corpo', c: 'Igiene' },
  { n: 'Crema solare', c: 'Igiene' },
  { n: 'Lamette', c: 'Igiene' },
  { n: 'Carta igienica', c: 'Igiene' },
  { n: 'Fazzoletti', c: 'Igiene' },
  { n: 'Cotton fioc', c: 'Igiene' },
  { n: 'Detersivo pavimenti', c: 'Pulizia' },
  { n: 'Detersivo piatti', c: 'Pulizia' },
  { n: 'Detersivo bucato', c: 'Pulizia' },
  { n: 'Ammorbidente', c: 'Pulizia' },
  { n: 'Candeggina', c: 'Pulizia' },
  { n: 'Disinfettante', c: 'Pulizia' },
  { n: 'Sgrassatore', c: 'Pulizia' },
  { n: 'Panni carta', c: 'Pulizia' },
  { n: 'Spugne', c: 'Pulizia' },
  { n: 'Sacchetti immondizia', c: 'Pulizia' },
  { n: 'Guanti', c: 'Pulizia' },
  { n: 'Pile', c: 'Elettronica' },
  { n: 'Lampadina', c: 'Elettronica' },
  { n: 'Cuffie', c: 'Elettronica' },
  { n: 'Cavo USB', c: 'Elettronica' },
  { n: 'Calzini', c: 'Abbigliamento' },
  { n: 'Mutande', c: 'Abbigliamento' },
  { n: 'Maglietta', c: 'Abbigliamento' },
  { n: 'Pantaloni', c: 'Abbigliamento' },
  { n: 'Felpa', c: 'Abbigliamento' },
];
